### ISSUE TITLE
New Outlier Report limited to GenCC genes

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-google-sheets#8]
Non-VCEP Outlier Report

Report of medically significant conflicts limited to genes that are not part of a VCEP's scope, filtered for only variants in the Genes that are Strong or Definitive on the GenCC list  

Due by Feb 20th

**Comment by larrybabb** [comment]
Heidi requested this for Julie to help her with priorities.

**Comment by larrybabb** [comment]
@dazzariti and Heidi 
I think this is going to be a fairly big report because I calculate 3,425 genes in genCC that have at least one of D-M-S classification(s).
In clinvar there are 1.5million clinvar variants associated that many genes.

Maybe we can break it down into a smaller subset because I think the google sheet will not work very well at that scale.

**Comment by larrybabb** [comment]
@dazzariti I agree this can archived (since we didn't do it).
